openapi: "3.0.0"
info:
  title: "Showtime Service API"
  version: "1.0.0"
  description: "API for managing showtimes and movie schedules"

servers:
  - url: "http://localhost:3202"

paths:
  /:
    get:
      summary: "Get a welcome message"
      responses:
        200:
          description: "Successful response"
          content:
            text/html:
              example: "<h1 style='color:blue'>Welcome to the Showtime service!</h1>"

  /showtimes:
    get:
      summary: "Get the showtime schedule"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              example: [{"date": "2023-01-01", "movies": [{"id": 1, "title": "Movie 1", "start_time": "18:00"}, {"id": 2, "title": "Movie 2", "start_time": "20:00"}]}]

  /showmovies/{date}:
    get:
      summary: "Get movies by date"
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              example: [{"id": 1, "title": "Movie 1", "start_time": "18:00"}, {"id": 2, "title": "Movie 2", "start_time": "20:00"}]
        400:
          description: "Date not found"
          content:
            application/json:
              example: {"error": "Date not found"}
