# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"\x1c\n\x0cShowtimeDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"(\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"+\n\x0b\x41llSchedule\x12\x1c\n\tschedules\x18\x01 \x03(\x0b\x32\t.Schedule\"\x0f\n\rShowtimeEmpty2q\n\x08Showtime\x12\x31\n\x13GetShowMoviesByDate\x12\r.ShowtimeDate\x1a\t.Schedule\"\x00\x12\x32\n\x10GetListShowtimes\x12\x0e.ShowtimeEmpty\x1a\x0c.AllSchedule\"\x00\x62\x06proto3')



_SHOWTIMEDATE = DESCRIPTOR.message_types_by_name['ShowtimeDate']
_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
_ALLSCHEDULE = DESCRIPTOR.message_types_by_name['AllSchedule']
_SHOWTIMEEMPTY = DESCRIPTOR.message_types_by_name['ShowtimeEmpty']
ShowtimeDate = _reflection.GeneratedProtocolMessageType('ShowtimeDate', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIMEDATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ShowtimeDate)
  })
_sym_db.RegisterMessage(ShowtimeDate)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

AllSchedule = _reflection.GeneratedProtocolMessageType('AllSchedule', (_message.Message,), {
  'DESCRIPTOR' : _ALLSCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:AllSchedule)
  })
_sym_db.RegisterMessage(AllSchedule)

ShowtimeEmpty = _reflection.GeneratedProtocolMessageType('ShowtimeEmpty', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIMEEMPTY,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ShowtimeEmpty)
  })
_sym_db.RegisterMessage(ShowtimeEmpty)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHOWTIMEDATE._serialized_start=18
  _SHOWTIMEDATE._serialized_end=46
  _SCHEDULE._serialized_start=48
  _SCHEDULE._serialized_end=88
  _ALLSCHEDULE._serialized_start=90
  _ALLSCHEDULE._serialized_end=133
  _SHOWTIMEEMPTY._serialized_start=135
  _SHOWTIMEEMPTY._serialized_end=150
  _SHOWTIME._serialized_start=152
  _SHOWTIME._serialized_end=265
# @@protoc_insertion_point(module_scope)
