openapi: "3.0.0"
info:
  title: "User Service API"
  version: "1.0.0"
  description: "API for managing users and their related data"

servers:
  - url: "http://localhost:3203"

paths:
  /:
    get:
      summary: "Get a welcome message"
      responses:
        200:
          description: "Successful response"
          content:
            text/html:
              example: "<h1 style='color:blue'>Welcome to the User service!</h1>"

  /users/{userid}:
    get:
      summary: "Get user by ID"
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              example: {"id": "chris_rivers", "name": "Chris Rivers", "last_active": 123456789}
        400:
          description: "User ID not found"
          content:
            application/json:
              example: {"error": "User ID not found"}

  /users/bookings/{userid}:
    get:
      summary: "Get user bookings by ID"
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              example: {"bookings": [{"id": 1, "date": "2023-01-01", "movies": [1, 2, 3]}]}
        404:
          description: "User ID not found"
          content:
            application/json:
              example: {"error": "User ID not found"}

  /users/infomovies/{userid}:
    get:
      summary: "Get information about movies for a user by ID"
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              example: [{"id": 1, "title": "Movie 1", "rating": 4.5, "director": "Director 1"}, {"id": 2, "title": "Movie 2", "rating": 3.8, "director": "Director 2"}]
        404:
          description: "User ID not found"
          content:
            application/json:
              example: {"error": "User ID not found"}
